### ISSUE TITLE
train.csv是怎么生成的呀，可以提供方法和这个数据集吗

### ISSUE THREAD

**Issue by Monicaqqqq** [TurboWay/bigdata_analyse#3]

**Comment by TurboWay** [comment]
最底部增加了 train.csv 的生成方法，[aa20b4d](https://github.com/TurboWay/bigdata_analyse/commit/aa20b4dca2d96dc1e10e8818b4b445e1827d160a)

时间比较久远，当时的清洗逻辑已经不记得了，可以自行调整。
